title: 許富淵的 Arduino 雜記
description: "A Jekyll Blog Theme For Arduino 雜記"
author:
  name: "許富淵"
  email: "student.fuyuanhsu@gmail.com"
  url: "https://fuyuanhsu.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2018"

theme: jekyll-theme-architect